# docker-compose.yml

version: "3.7"

services:
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
        volume:
          nocopy: true
      # - type: bind
      #   source: ~/AppData/Roaming/MongoDB/data_docker
      #   target: /data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672"
      - "15672:15672"
    env_file: .env
  crontris:
    image: tristanbrown/crontris
    env_file: .env
volumes:
  mongodata: