# docker-compose.yml

version: "3.7"

services:
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - mongotemp:/tmp/mongodb
    labels:
      - docker-volume-backup.exec-pre-backup=mongodump --archive=/tmp/mongodb/mongo.dump
      - docker-volume-backup.exec-post-backup=rm -rfv /tmp/mongodb
      # Restore backup by cp into mongodb container, $ mongorestore --archive=mongo.dump
  backup:
    image: futurice/docker-volume-backup:2.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - mongotemp:/backup/mongodb:ro
      - ${BACKUP_DIR}:/archive
    environment:
      - BACKUP_CRON_EXPRESSION=${BACKUP_CRON_EXPRESSION}
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  crontris:
    image: tristanbrown/crontris:${CRONTRIS_TAG:-latest}
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - COMPUTERNAME=${COMPUTERNAME}
volumes:
  mongodata:
  mongotemp:
